# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    container_name: qairlines_backend
    ports:
      - 5199:5199
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    #   MYSQL_HOST: mysql
    #   MYSQL_USER: root
    #   MYSQL_PASSWORD: 12345678
    #   MYSQL_DB: qairlines
    volumes:
      - ~/docker-ingress/qairlines/appsettings.json:/app/appsettings.json
      - ~/docker-ingress/qairlines/appsettings.Development.json:/app/appsettings.Development.json
      - ~/docker-ingress/qairlines/appsettings.Production.json:/app/appsettings.Production.json